// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultivalueDnsRecord) DeepCopyInto(out *MultivalueDnsRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultivalueDnsRecord.
func (in *MultivalueDnsRecord) DeepCopy() *MultivalueDnsRecord {
	if in == nil {
		return nil
	}
	out := new(MultivalueDnsRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultivalueDnsRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultivalueDnsRecordList) DeepCopyInto(out *MultivalueDnsRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultivalueDnsRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultivalueDnsRecordList.
func (in *MultivalueDnsRecordList) DeepCopy() *MultivalueDnsRecordList {
	if in == nil {
		return nil
	}
	out := new(MultivalueDnsRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultivalueDnsRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultivalueDnsRecordSpec) DeepCopyInto(out *MultivalueDnsRecordSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultivalueDnsRecordSpec.
func (in *MultivalueDnsRecordSpec) DeepCopy() *MultivalueDnsRecordSpec {
	if in == nil {
		return nil
	}
	out := new(MultivalueDnsRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultivalueDnsRecordStatus) DeepCopyInto(out *MultivalueDnsRecordStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultivalueDnsRecordStatus.
func (in *MultivalueDnsRecordStatus) DeepCopy() *MultivalueDnsRecordStatus {
	if in == nil {
		return nil
	}
	out := new(MultivalueDnsRecordStatus)
	in.DeepCopyInto(out)
	return out
}
